#!/usr/bin/env bash

if [ -d "./bin" ]; then
  echo "Error: The current directory is not empty. Please remove all contents within this directory and try again."
  exit 1
fi

# Clone only the compose folder
git init -qqq
git remote add origin https://github.com/edwinflopez/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose

# Remove created git config, we don't care about it once it is setup.
mv compose/* ./
rm -rf compose/.vscode
rm -rf compose/.gitignore
rm -rf ./compose
rm -rf ./.git

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh
